name: cixian
description: "词冼 - 背单词软件（V0.0.1）"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/wordbooks/